- hosts: all
  become: true
  tasks:
  - name: New repos
    template: 
      src: curator.repo.j2
      dest: /etc/yum.repos.d/curator.repo

  - name: Remove New version
    yum:
      name: kibana-6.5.4-1.x86_64
      state: absent

  - name: Install old version
    yum:
      name: kibana-6.4.0-1.x86_64
      state: present
  
  - name: Copy configuration file
    template:
      src: kibana.yml.j2
      dest: /etc/kibana/kibana.yml
  
  - name: Restart Kibana
    service: 
      name: kibana
      state: restarted