- hosts: all
  become: true
  tasks:
  - name: Testando
    file:
      path: "/tmp/testando"
      state: touch
  - name: Instalacao dinamica
    yum:
      name: "{{ name_pkg }}"
      state: present