---
# tasks file for cerebro
- name: Download Cerebro RPM
  get_url:
    url: https://github.com/lmenezes/cerebro/releases/download/v0.9.2/cerebro-0.9.2-1.noarch.rpm
    dest: /tmp/cerebro.rpm

- name: Install Cerebro
  yum:
    name: /tmp/cerebro.rpm
    state: present
  notify: restart cerebro

- name: Copy configuration Cerebro
  template:
    src: application.conf.j2
    dest: /etc/cerebro/application.conf
  notify: restart cerebro

- name: Enable Cerebro
  systemd:
    name: cerebro
    enabled: yes
    state: started
  notify: restart cerebro
