---
# tasks file for common
- name: Disabilitando selinux
  selinux:
    state: disabled

- name: Adicionando repositorio epel
  yum:
    name: epel-release
    state: present

- name: Upgrade system
  yum:
    name: "*"
    state: latest

- name: Pacotes comuns
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: present
  loop:
    - htop
    - vim
    - wget
    - curl
    - net-tools
    - python
    - python-pip
    - telnet
    - java-11-openjdk
