---
# tasks file for elasticsearch
- name: Adicionando chave GPG
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Adicionando repositorio
  template:
    src: elasticsearch.repo.j2
    dest: /etc/yum.repos.d/elasticsearch.repo

- name: Instalacao do Elasticsearch
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - elasticsearch

- name: Criando diretorio data
  file:
    path: /data
    owner: root
    group: elasticsearch
    state: directory
    mode: 0770

- name: Definindo configuracao
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660
  notify: restart elasticsearch

- name: Definindo configuracao
  template:
    src: elastic-certificates.p12
    dest: /etc/elasticsearch/elastic-certificates.p12
    owner: elasticsearch
    group: elasticsearch
    mode: 0600
  notify: restart elasticsearch

- name: Java Heap
  template:
    src: jvm.options.j2
    dest: /etc/elasticsearch/jvm.options

- name: Iniciando servico
  systemd:
    name: elasticsearch
    state: started
    enabled: yes

- name: Aguarde o elasticsearch
  wait_for:
    host: localhost
    port: 9200
    delay: 3
    timeout: 300
